name: django_client_framework
version: 1.1.0
description: The Dart implementation of the Django Client Framework
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  ansicolor: ^2.0.1
  http: ^0.13.1
  logger: ^1.1.0
  uuid: ^3.0.5
dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
