name: django_client_framework
version: 1.0.0
description: The Dart implementation of the Django Client Library
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.1
dev_dependencies:
  test: ^1.19.3
